### ISSUE TITLE
Error and master password prompt dont respect passed arguments

### ISSUE THREAD

**Issue by AlecsFerra** [mattydebie/bitwarden-rofi#67] opened 2021-07-26 17:04 UTC
the error and master password prompt should respect the rofi arguments passed by the user

**Comment by ickerwx** [comment] 2021-08-27 13:39
This is probably a duplicate of #53

**Comment by mattydebie** [comment] 2023-04-17 08:15
fixed in #53 i think

**Closed as completed by mattydebie** 2023-04-17 08:15 UTC
